version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    # Uncomment the following lines if you need to mount volumes
    # volumes:
    #   - ./some-local-config:/path/in/container
